### ISSUE TITLE
amphibious inversion

### ISSUE THREAD

**Issue by jglin001001** [HongjianFang/DSurfTomo#15]
Hello:

I would like to know if this program can be applied to amphibious inversion of seismic surface waves? (Currently, I have OBS data and data from land stations, both land and ocean are continental crust.) If possible:
﻿
How should I set the depth and speed settings for the initial MOD? The depth I made is 30, 40, 50, ..., 100km, with a water depth of approximately 5km. It seems that the depth of the ocean does not significantly affect the seismic wave velocity at the same depth? (such as the speed below the ocean and land at a distance of 30km).

Thanks!

**Comment by HongjianFang** [comment]
Hi there,
   Thanks for the inquiry. Since I have never tried to use the code for inverting amphibious data, I'm not sure if it will work. My concern is about the difference in boundary conditions, so the calculation of dispersion with an water layer affect the results (more severe for short period?). Anyway, please keep me updated with your progress.

Cheers,
Hongjian Fang
