### ISSUE TITLE
What migh cause it that the absolute velocity of the inversion cannot converge to a reasonable range？

### ISSUE THREAD

**Issue by LevCarlo** [HongjianFang/DSurfTomo#6]
Refer to previous S velocity model，I give a linear model as default. During the preliminary attempt, I give a wide velocity range(minimum velocity, maximum velocity), but the extreme value(the highest and lowest velocity) of inversion result tend to the boundary value of the velocity range, rather than reasonable value(i.e. while depth is 10km or 0km, the S velocity is about to 4km/s or 2.5km/s). Besides, with each iteration,  the inversion result shows characteristic that high velocity is more higher, low velocity is more lower, which seems to be trapped in local minima. What might cause this situation? Except modifying the priori velocity range, is it necessary to modify other parameters, or check my dispersion curves?

**Comment by HongjianFang** [comment]
Sorry for the late reply.
I would suggest increasing the regularization parameters (the smoothing and damping) to make sure the velocity variation at each iteration does not change dramatically. The largest variation should be smaller than 0.4 km/s based on my experience, otherwise, the model update would be too large and excess the specified boundary values.
