### ISSUE TITLE
error in computing sensitivity matrix

### ISSUE THREAD

**Issue by asadeghib** [HongjianFang/DSurfTomo#7]
Hi @HongjianFang 
I am using DSurfTomo (v1.3) to invert 112422 Rayleigh phase velocity measurements. First I encountered this error:
Index '201' of dimension 1 of array 'rthk' above upper bound of 200Index '201' of dimension 1 of array 'rthk' above upper bound of 200
So I increased the 200 default values of the NL and NLAY parameters to 300 in surfdisp96.f and CalSurfG.f90. 
Now I get this error while the code tries to compute sensitivity matrix:

DSurfTomo(55526,0x114dc1dc0) malloc: Region cookie corrupted for region 0x7fdbdf600000 (value is bd8fbf3f)
DSurfTomo(55526,0x114dc1dc0) malloc: *** set a breakpoint in malloc_error_break to debug

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x10818872c
#1  0x108187ad3
#2  0x7fff673c042c
Abort trap: 6

I also tried DSurfTomo (v2) and here is the error:

DSurfTomo(57162,0x10fc7cdc0) malloc: Incorrect checksum for freed object 0x7f876bd009b8: probably modified after being freed.
Corrupt value: 0xbcec818dbd19b28d
DSurfTomo(57162,0x10fc7cdc0) malloc: *** set a breakpoint in malloc_error_break to debug

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x10b6ae72c
#1  0x10b6adad3
#2  0x7fff673c042c
Abort trap: 6

**Comment by HongjianFang** [comment]
Hi @asadeghib,
   I think there are memory issues since you have a large data set and too many model parameters. Is there any particular reason why you use more than 50 layers? A few things you can try:
  1, decrease the sparse fraction parameter;
  2, decrease minthk to 2;
 This would still take a substantial amount of time, so if I were you, I'll first decrease the model dimensions (nx,ny,nz) to see how's the result look like.

Hope this helps.
Hongjian

**Comment by chinu739** [comment]
Hi HongjianFang,
In order to acquinted and practice I tried your codes as mentioned in the manual, but after running '../src/DSurfTomo DSurfTomo.in' no output files are generated. I get something like this
computing sensitivity matrix...
 Rayleigh wave phase velocity depth kernel
 Source lies outside bounds of model (lat,long)=   -1.03841651E+27   9.90839927E-40
 TERMINATING PROGRAM!!!
could you please explain where am I going wrong and correct me so that I could proceed further
Thanking you in advance

**Comment by HongjianFang** [comment]
Hello @chinu739,
  You may need to revise your origin points and grid interval so that all the sources and receivers are within the study region. Hope this helps.

Cheers,
Hongjian

**Comment by asadeghib** [comment]
Hi @chinu739 
I guess you need to check if all the sources and receivers are in the region defined by the following parameters in the DSurfTomo.in file. 
goxd, gozd, dvxd, dvzd, nx, ny
